### ISSUE TITLE
create fakeorder

### ISSUE THREAD

**Issue by josamho** [Cdiscount/API-MarketPlace-SDK-PHP#30]
hey !
On the Api Library, we have a Sandbox list, and it's say that we can do fake order, and simulate payement. But i dont see any files to do this on the SDK php... Someone know how to do this ?

**Comment by gregz1** [comment]
Hello,

there is an API here : https://wsvc.cdiscount.com/MarketplaceSandboxAPIService.svc
But it is not exactly up to date.

Otherwise you can create a ticket in the help section of your Cdiscount backoffice to ask for test order on their test environment.
It is the best way to be sure that  the datacontract will be exactly the same than the production datacontract.

**Comment by josamho** [comment]
Ok, Thanks ! :)
